### ISSUE TITLE
'snapstack_msgs.msg' file missing

### ISSUE THREAD

**Issue by WangCH69** [mit-acl/mader#10] opened 2022-01-01 14:19 UTC
I followed the setup steps in the description, however, an error occured when running 'bash src/mader/install_and_compile.sh'.

The error is :
'Could not find a package configuration file provided by "snapstack_msgs" with any of the following names:
snapstack_msgsConfig.cmake
snastack_msgs-config.cmake '

And this directly led to building failure of the package named "decomp_test_node"
Could anyone please help me with this one?

**Comment by jtorde** [comment] 2022-12-12 17:06
Hi!,

Are you still finding this issue? I cannot reproduce it on my side. 

Did [these commands](https://github.com/mit-acl/mader/blob/master/install_and_compile.sh#L37) run without errors?

**Comment by jtorde** [comment] 2023-03-10 11:59
I am closing this for now, feel free to reopen if you are still finding this issue

**Closed by jtorde** 2023-03-10 11:59 UTC
